# Generated by Django 5.0.7 on 2025-10-25 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_userprofile_activity_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=50)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_read_list', to='core.userprofile')),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user_profile', 'story_id')},
            },
        ),
    ]
